src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Get creative and think of a title! ❌")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Content can not be blanc! ❌")
     */
    private $content;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Translated content can not be blanc! ❌")
     */
    private $contentNl;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Please fill in publish date!  ❌")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFileName;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="articles")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getContentNl(): ?string
    {
        return $this->contentNl;
    }

    public function setContentNl(?string $content_nl): self
    {
        $this->contentNl = $content_nl;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->imageFileName;
    }

    public function setImageFileName(?string $imageFileName): self
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }

    public function getImagePath()
    {
        return 'images/'.$this->imageFileName;
    }

    public function getImageNameWithoutExtention()
    {
        $arr = explode(".", $this->imageFileName);
        return $arr[0];
    }

    public function incrementHeartCount() : self
    {
        $this->heartCount = $this->heartCount + 1;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function getAuthorOfArticle(): string
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

//    /**
//     * @Assert\Callback
//     */
    /*public function validate(ExecutionContextInterface $context)
    {
        if ((strpos($this->getImageFileName(), 'png') == false)
            && (strpos($this->getImageFileName(), 'jpg') == false)
            && (strpos($this->getImageFileName(), 'jpeg') == false)
        )
        {
            $context->buildViolation('The file must be of format .jpg or .png or .jpeg ❌')
                ->atPath('imageFileName')
                ->addViolation();
        }
    }*/



}

src/Controller/ArticleController.php
<?php


namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Repository\ArticleRepository;
use App\Service\MarkdownHelper;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Component\Intl\Timezones;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;

class ArticleController extends AbstractController
{
/*@Route("/{locale}", name="app_homepage", locale="en", requirements = {"locale": "en|nl"})*/



    /**
     * @Route("/")
     *      defaults={"%locale%":"en"},
     *     )
     * @Route("/{_locale}",
     *     name="app_homepage",
     *     requirements={
     *         "_locale":"en|nl",
     *     }
     * )
     */

    public function homepage(ArticleRepository $repository)
    {

        $articles = $repository->findAllPublishedOrderByNewest();

        return $this->render('article/homepage.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/news/{slug}")
     *      defaults={"%locale%":"en"},
     *     )
     * @Route("/{_locale}/news/{slug}",
     *     name="article_show",
     *     requirements={
     *         "_locale":"en|nl",
     *     }
     * )
     */

    public function show(Request $request, $slug, /*MarkdownHelper $markdownHelper, */EntityManagerInterface $em, CsrfTokenManagerInterface $csrfTokenManager)
    {
        if ($request->isMethod('post')) {

            $this->csrfTokenManager = $csrfTokenManager;
            $author = $request->request->get('author');
            $article_id = $request->request->get('article_id');
            $article = $this->getDoctrine()
                ->getRepository(Article::class)
                ->find($article_id);
            $content = $request->request->get('content');
            $token= $request->request->get('_csrf_token');
            if (!$this->isCsrfTokenValid('authenticate', $token))
            {
                return $this->redirectToRoute('app_error403');
            }
            $comment = new Comment();
            $comment->setAuthorName($author)
                    ->setContent(<<<EOF
$content
EOF
)
                    ->setArticle($article);
            $em->persist($comment);
            $em->flush();
        }
        $repository = $em->getRepository(Article::class);
        /** @var Article $article */
        $article = $repository->findOneBy(['slug' => $slug]);
        if (!$article)
        {
            throw $this->createNotFoundException(sprintf('No article for slug "%s"', $slug));
        }

        /*$comments = [
            'The Lyrids, which peak during late April, are one of the oldest known meteor showers: 
            Lyrids have been observed for 2,700 years. (The first recorded sighting of a Lyrid meteor 
            shower goes back to 687 BC by the Chinese.)',
            'The Eta Aquarids peak during early-May each year. Eta Aquarid meteors are known for their 
            speed. These meteors are fast—traveling at about 148,000 mph (66 km/s) into Earth\'s atmosphere.
             Fast meteors can leave glowing "trains" (incandescent bits of debris in the wake of the meteor)
              which last for several seconds to minutes. In general, 30 Eta Aquarid meteors can be seen 
              per hour during their peak.',
            'The Delta Aquariids are active beginning in mid-July and are visible until late-August. 
            These faint meteors are difficult to spot, and if there is a moon you will not be able to 
            view them. If the moon is not present, your best chance to see the Delta Aquariids is when 
            meteor rates rise during the shower\'s peak at the end of July.'];*/

        /*$articleIntro = <<<EOF
At the very beginning of our solar system, **before** there was an Earth, Jupiter or
Pluto, a massive swirling cloud of dust and gas circled the young Sun. The dust 
particles in this disk collided with each other and formed into larger bits of rock. 
This process continued until they reached the size of boulders. Eventually this 
process of accretion formed the planets of our solar system.

Billions of small space rocks never evolved. Amazingly, many of these mysterious
worlds have been *altered very little* in the 4.6 billion years since they first 
formed. Their relatively pristine state makes the comets, asteroids and some meteors 
wonderful storytellers with much to share about what conditions were like in the 
early solar system. They can reveal secrets about our origins, chronicling the 
processes and events that led to *the birth of our world.* They might offer clues
about where the water and raw materials that made life possible on Earth came
from.
EOF;

        $articleIntro = $markdownHelper->parse(
            $articleIntro
        );*/

        return $this->render('article/show.html.twig', [
            'article' => $article,
           /* 'comments' => $comments,*/
        ]);
    }

    /**
     * @Route("/news/{slug}/heart", name="article_show_toggle", methods = {"POST"})
     */

    /*public function toggleArticleHeart($slug, LoggerInterface $logger)
    {
        $logger->info('Article is being hearted');
        return $this->json(['hearts' => rand(5, 100)]);
    }*/

    public function toggleArticleHeart(LoggerInterface $logger, Article $article, EntityManagerInterface $em)
    {
        $article->incrementHeartCount();
        $em->flush();
        $logger->info('Article is being hearted!');
        return new JsonResponse(['hearts' => $article->getHeartCount()]);
    }

}

src/Controller/BaseController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BaseController extends AbstractController
{
    protected function getUser() :User
    {
        return parent::getUser();
    }
}

templates/article/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row mt-4">
            <div class="col-12 text-center">
                <div id= "cookie_container" class="cookie p-3 d-flex justify-content-between align-items-center hide">
                    <div class="px-3">
                        <h5>{% trans %}Hello, this site uses cookies{% endtrans %} &#x1F36A!</h5>
                        <p>{% trans %}We use session, functional and anonymous statistic cookies to make your visit to the website as pleasant as possible.{% endtrans %}</p>
                        <p>{% trans %}To find out more, read our{% endtrans %}
                            <a href="{{ path('app_privacy_policy') }}">{% trans %}privacy policy{% endtrans %}</a> {% trans %}and{% endtrans %} <a href="{{ path('app_cookie_policy') }}">{% trans %}cookie policy{% endtrans %}</a>.</p>
                    </div>
                    <div class="pr-3">
                        <button class="btn btn-dark color transform cookie-agree-btn mb-1" id="btnOK">{% trans %}Agree{% endtrans %}</button>
                        <button class="btn btn-dark color transform cookie-disagree-button ml-2 mb-1" id="btnOK">{% trans %}Disagree{% endtrans %}</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-12 text-center">
                <h4>{% trans %}Newsite which spread light on dark matters{% endtrans %}:</h4>
                <h1>{% trans %}The Infinite Space Bar{% endtrans %}</h1>
            </div>
        </div>

        <div class="row mt-4">

            <!-- Article List -->

            <div class="col-sm-12 col-md-7">

                <!-- Article 1 -->
                <a href="{{ path('article_show',{slug:'The-9-best-meteor-showers-to-watch-in-2020-370'}) }}">
                    <div class="mb-4 pb-3 border">
                        <img class="img-fluid mb-3 border-bottom" src="{{ asset('images/meteors_shower.jpg') }}" alt="meteor shower">
                        <h3 class="text-center mt-2">{% trans %}The <span class="color">9 best meteor showers</span> to watch <br>in 2020{% endtrans %}</h3>
                    </div>
                </a>

                <a href="{{ path('article_show',{slug:'Astroids-Comets-And-Planets-663'}) }}">
                    <div class="mb-4 pb-3 border">
                        <img class="img-fluid mb-3 border-bottom" src=" {{ asset('images/416_16_psyche_main.jpg') }} " alt="astroid 416">
                        <h3 class="text-center mt-2">{% trans %}<span class="color">Astroids</span>, <span class="color">Comets</span> and <span class="color">Planets</span>{% endtrans %}</h3>
                    </div>
                </a>
                <!-- Supporting Articles -->

                {#<div class="my-1 border">
                        <img class="article-img"  src="{{ asset('images/nasa-asteroids.jpg') }}">
                    <div class="article-title d-inline-block pl-3 align-middle">
                        <br>
                        <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}"> Mike Ferengi </span>
                        <span class="pl-5 article-details float-right"> 3 hours ago</span>
                    </div>
                </div>#}
                {% for article in articles %}
                <div class="my-1 border mb-4">
                    <div class="row">

                            <div class="col-4 text-center">
                                <a href="{{ path('article_show', {slug: article.slug}) }}" >
                                    <img src="{{ asset(article.imagePath)|imagine_filter('squared_thumbnail_small') }}" class="img-fluid" alt ="planet Mercury">
                                </a>
                            </div>
                            <div class="col-8">
                                <a href="{{ path('article_show', {slug: article.slug}) }}">
                                    <div class="article-title align-middle">
                                        <p> <span class="color">{{ article.title|trans }} </span><br><span>{{ article.comments|length }} {% trans %}comments{% endtrans %}</span></p>
                                        <div class="mt-2" style = "color: white">
                                            <span class=""><img class="article-author-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}" alt="{{article.author}}"> {{article.author}} </span>
                                            <p class="article-details "> {{ article.publishedAt ? article.publishedAt | ago  : 'unpublished'}}
                                            {% trans %}on{% endtrans %}
                                            {% if (app.request.locale  == 'nl') %}
                                                {{ article.publishedAt ? article.publishedAt | format_datetime('medium', 'none', locale='nl')  : 'unpublished'}}
                                            </p>
                                            {% else %}
                                                {{ article.publishedAt ? article.publishedAt | format_datetime('medium', 'none', locale='en')  : 'unpublished'}}
                                            {% endif %}
                                            <p class="article-details mt-1">
                                                {% trans %}tags{% endtrans %}:&nbsp
                                                {% for tag in article.tags %}
                                                    <span class="badge badge-secondary">
                                                        {{ tag.name|trans }}
                                                    </span>
                                                {% endfor %}
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </div>

                    </div>
                </div>
                {% endfor %}

                {#<div class="my-1 border mb-3">
                    <a href="#">
                        <img class="article-img" src="{{ asset('images/light-speed.jpg') }}" alt="light speed">
                        <div class="article-title d-inline-block pl-3 align-middle">
                            <a href="#"><span class="color">Light Speed Travel: </span><br><span>The Speed Of Light Is Not About Lightk</span></a>
                            <div class="mt-2">
                                <span class="align-left"><img class="article-author-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}" alt="astronautt Oort"> Amy Oort </span>
                                <span class="pl-5 article-details"> 2 weeks ago</span>
                            </div>
                        </div>
                    </a>
                </div>#}

            </div>

            <!-- Right bar ad space -->

            <div class="col-sm-12 col-md-5 text-center">
                <div class="ad-space mx-auto mb-4 border">
                    <img class="img-fluid border mb-2" src="{{ asset('images/ice-full.jpg') }}" alt="ice in space">
                    <h3 class="font-weight-bold">Cosmos Magazine:</h3>
                    <p class="font-italic">{% trans %}Main article{% endtrans %}: {% trans %}Interstellar ice may hold the secret to life{% endtrans %}</p>
                    <button class="btn btn-dark mb-3">{% trans %}Buy Now{% endtrans %}!</button>
                </div>

                <div class="pb-2 pt-2 px-5 border">
                    <h3 class="text-center pb-3 mt-2">{% trans %}Famous quotes by astronauts{% endtrans %}</h3>
                    <h5><i>"{% trans %}That’s one small step for a man, one giant leap for mankind{% endtrans %}.”</i></h5>
                    <p><a href="#" class="text-uppercase">Neil Armstrong </a>- Apollo 11 {% trans %}mission{% endtrans %}</p>
                    <h5 class="pt-4"><i>"{% trans %}The earth must become as it appears&colon; blue and white, not capitalist or Communist; blue and white, not rich or poor; blue and white, not envious or envied{% endtrans %}."</i> </h5>
                    <p><a href="#" class="text-uppercase">Michael Collins</a> - Apollo 11 {% trans %}mission{% endtrans %}</p>
                    <h5 class="pt-4"><i>"{% trans %}I looked and looked but I didn't see God{% endtrans %}."</i></h5>
                    <p><a href="#" class="text-uppercase">Yuri Gagarin </a>- {% trans %}first man in space{% endtrans %}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/cookie_banner_consent.js') }}"></script>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Read {{ article.title }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href ="{{ asset('css/form.css') }}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mt-4 mb-3 d-flex align-items-center">
            <div class="col-6 col-sm-5">
                <figure>
                    <img class="img-fluid show-article-img"
                         src="{{ asset(article.imagePath)|imagine_filter('rectangled_thumbnail_medium') }}">
                    <a href="{{ asset(article.imagePath)|imagine_filter('my_ratio_up_scale_filter') }}"><span><i class="fas fa-expand-arrows-alt expand"></i></span></a>
                    <figcaption class="ml-1">-{{ article.imageNameWithoutExtention}}-</figcaption>
                </figure>

            </div>
            <div class="col-6 col-sm-7 text-center">
                <h1 class="title mb-4">{{ article.title|trans }}</h1>
                <span class="align-left article-details"><img class="article-author-img rounded-circle"
                    src="{{ asset('images/anakin-skywalker.png') }}"> {{ article.author }}
                </span>
                <span class="pl-2 article-details">
                    {{ article.publishedAt ? article.publishedAt | ago  : 'unpublished'}}
                    {% trans %}on{% endtrans %}
                    {% if (app.request.locale  == 'nl') %}
                        {{ article.publishedAt ? article.publishedAt | format_datetime('medium', 'none', locale='nl')  : 'unpublished'}}
                    {% else %}
                        {{ article.publishedAt ? article.publishedAt | format_datetime('medium', 'none', locale='en')  : 'unpublished'}}
                    {% endif %}
                </span>
                <span class="pl-2 article-details"> <span class="js-like-article-count"> {{ article.heartCount }}</span>
                    <a href="#" class="ml-1 fa fa-heart-o like-article js-like-article" data-link = {{ article.slug }}></a>
                </span>
                <p class="article-details mt-2">
                    tags:&nbsp
                    {% for tag in article.tags %}
                        <span class="badge badge-secondary">
                            {{ tag.name|trans }}
                        </span>
                    {% endfor %}
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                {% if (app.request.locale == 'en')%}
                    {{ article.content|raw }}
                {% else %}
                    {{ article.contentNl|raw }}
                {% endif %}

                {#<h4>Current Counts:</h4>
                <ul>
                    <li><strong>Known Asteroids:</strong> <span class="color">57 5269</span></li>
                    <li><strong>Known Comets:</strong> <span class="color">3 611</span></li>
                </ul>
                <br/>
                {{ articleParagraph1|raw }}
                {{ articleParagraph2|raw }}#}
            </div>
            <div class="col-12 mt-3">
                <p class="share-icons mb-5"><span class="pr-1">{% trans %}Share{% endtrans %}:</span>
                    <i class="pr-1 fa fa-facebook-square"></i><i class="pr-1 fa fa-twitter-square"></i><i
                            class="pr-1 fa fa-reddit-square"></i><i class="pr-1 fa fa-share-alt-square"></i>
                </p>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                <h3>{%trans%}Comments{% endtrans %}<i class="pl-3 fa fa-comment"></i> ({{ article.comments|length }})</h3>
            </div>
        </div>

        {% if is_granted('ROLE_USER') == true %}
            <div class="row mb-2">
                <div class="col-sm-12">
                    <img class="comment-img rounded-circle"
                         src="{{ asset('images/astronaut-profile.png') }}">
                    <div class="d-inline-block pl-3 align-items-center">
                        <span class="commenter-name">{{ app.user }} {% trans %}if desired, you can add your comment to this article{% endtrans %}.</span>
                    </div>
                </div>
                <div class="col-sm-12">
                    <form method="post" novalidate autocomplete="off" class="mt-2 mb-3 py-3 px-5">
                        <div class="form-group mb-2" id="localeLanguage" data-language-type="{{ app.request.locale }}">
                            <div class="d-flex justify-content-between">
                                <label for="inputContent" class="required">{% trans %}New comment{% endtrans %}</label>
                                <span id="showErrorContent"class="invalid-feedback mb-1">
                                    <span class="form-error-icon badge badge-danger text-uppercase">Error</span>
                                    <span id="errorTextContent" class="form-error-message"></span>
                                </span>
                            </div>
                            {% set inputContentPlaceholder = "Place a comment on this article" %}
                            <textarea id="inputContent" name="content" class="form-control comment-form"
                                      rows="2" placeholder= "{{inputContentPlaceholder|trans}}" required></textarea>
                        </div>
                        <input type="hidden" name="_csrf_token"
                               value="{{ csrf_token('authenticate') }}"
                        >
                        <input type="hidden" name="author"
                               value="{{ app.user }}"
                        >
                        <input type="hidden" name="article_id"
                               value="{{ article.id }}"
                        >

                        <div class="text-right">
                            <button id="submitButton" type="submit" class="btn btn-dark">{% trans %}Submit comment{% endtrans %}</button>
                        </div>
                    </form>
                </div>
            </div>
        {% else %}
            <div class="row mb-2">
                <div class="col-sm-12">
                    <p class="bg-color p-2 text-center" >Do you also want to add comments to this article? <a href="{{ path('app_login') }}">Please sign in.</a></p>
                </div>
            </div>

        {% endif %}

        {% for comment in article.comments %}
        <div class="row">
            <div class="col-sm-12 mb-3">
                    <img class="comment-img rounded-circle"
                         src="{{ asset('images/anakin-skywalker.png') }}">
                    <span class="commenter-name">{{ comment.authorName }}</span>
                    <small>{{ comment.createdAt|ago }}</small>
                    <br>
                    {{ comment.content|trans }}
                    {% if is_granted('ROLE_USER') == true %}
                        <p><a href="#">{% trans %}Reply{% endtrans %}</a></p>
                    {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock body %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/article_show.js') }}"></script>
    {% if is_granted('ROLE_USER') == true %}
        <script src="{{ asset('js/check_comment.js') }}"></script>
        <script src="{{ asset('js/hide_error_message.js') }}"></script>
    {% endif %}
{% endblock %}